// <auto-generated />
using System;
using Lab7_1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab7_1.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240321200630_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("Lab7_1.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalBiomesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AnimalClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LimbCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalBiomesId");

                    b.HasIndex("AnimalClassId");

                    b.ToTable("Animals");
                });

            modelBuilder.Entity("Lab7_1.AnimalClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BiomesId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("EatId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BiomesId");

                    b.HasIndex("EatId");

                    b.ToTable("AnimalClass");
                });

            modelBuilder.Entity("Lab7_1.Biomes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimalBiomes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Biomes");
                });

            modelBuilder.Entity("Lab7_1.Eat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AnimalId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Calories")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EatName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AnimalId");

                    b.ToTable("Eat");
                });

            modelBuilder.Entity("Lab7_1.Animal", b =>
                {
                    b.HasOne("Lab7_1.Biomes", "AnimalBiomes")
                        .WithMany()
                        .HasForeignKey("AnimalBiomesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab7_1.AnimalClass", "AnimalClass")
                        .WithMany("Animals")
                        .HasForeignKey("AnimalClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimalBiomes");

                    b.Navigation("AnimalClass");
                });

            modelBuilder.Entity("Lab7_1.AnimalClass", b =>
                {
                    b.HasOne("Lab7_1.Biomes", null)
                        .WithMany("Animals")
                        .HasForeignKey("BiomesId");

                    b.HasOne("Lab7_1.Eat", null)
                        .WithMany("Animals")
                        .HasForeignKey("EatId");
                });

            modelBuilder.Entity("Lab7_1.Eat", b =>
                {
                    b.HasOne("Lab7_1.Animal", null)
                        .WithMany("AnimalEats")
                        .HasForeignKey("AnimalId");
                });

            modelBuilder.Entity("Lab7_1.Animal", b =>
                {
                    b.Navigation("AnimalEats");
                });

            modelBuilder.Entity("Lab7_1.AnimalClass", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Lab7_1.Biomes", b =>
                {
                    b.Navigation("Animals");
                });

            modelBuilder.Entity("Lab7_1.Eat", b =>
                {
                    b.Navigation("Animals");
                });
#pragma warning restore 612, 618
        }
    }
}
